version: '3.6'

services:
  redis:
    build:
        context: ../..
        dockerfile: ./docker.d/dockerfiles/Dockerfile-redis
    container_name: ${ENV}_${PROJECT_NAME}_redis
    restart: always
    environment:
     - REDIS_REPLICATION_MODE=master
    volumes:
      - $PWD/run/redis:/datamake
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - symfony-stack