version: '3.6'

services:
  mysql:
    build:
      context: ../..
      dockerfile: ./docker.d/dockerfiles/Dockerfile-mysql
    container_name: ${ENV}_${PROJECT_NAME}_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - TZ=${TIMEZONE}
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - $PWD/run/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - symfony-stack
